### ISSUE TITLE
Auto mode selector

### ISSUE THREAD

**Issue by CS-5** [Team4050/2023-charged-up#19]
Add dashboard control to allow drivers to select what auto mode to run on the fly. Important for when we may need to change our robot's starting position or strategy. 

For now, that selector should include the simple auto mode and also a "do nothing" mode.

**Comment by Kieth-the-25th** [comment]
Feature added in simple-autonomous branch.

- [ ] Merge simple-autonomous into main

**Comment by Kieth-the-25th** [comment]
All tasks complete!
